//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneCompanies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public int TypeId { get; set; }
        public int AbonentId { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual TypeNumber TypeNumber { get; set; }
    }
}
